// <auto-generated />
using System;
using Airsoft_equipment_tracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airsoft_equipment_tracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605150942_AddValidationConstraints")]
    partial class AddValidationConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Airsoft_equipment_tracker.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Novritsch"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tokyo Marui"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Invader Gear"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Vector Optics"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Specna Arms"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Titan Power"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cyma"
                        },
                        new
                        {
                            Id = 8,
                            Name = "BLS"
                        });
                });

            modelBuilder.Entity("Airsoft_equipment_tracker.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Primary"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Secondary"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gear"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Attachment"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Magazine"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Consumable"
                        });
                });

            modelBuilder.Entity("Airsoft_equipment_tracker.Models.EquipmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("EquipmentItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Name = "SSR90",
                            Notes = "Main outdoor replica",
                            Price = 549m,
                            PurchaseDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CategoryId = 2,
                            Name = "Glock 17",
                            Notes = "Sidearm",
                            Price = 180m,
                            PurchaseDate = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            CategoryId = 3,
                            Name = "Plate Carrier",
                            Notes = "Main carrier setup",
                            Price = 120m,
                            PurchaseDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            CategoryId = 4,
                            Name = "Red Dot Sight",
                            Notes = "Mounted on SSR90",
                            Price = 90m,
                            PurchaseDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 5,
                            CategoryId = 5,
                            Name = "Mid-Cap Magazine",
                            Notes = "120 round mid-cap",
                            Price = 15m,
                            PurchaseDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 6,
                            CategoryId = 3,
                            Name = "LiPo Battery 11.1V",
                            Notes = "Used for SSR90",
                            Price = 35m,
                            PurchaseDate = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 7,
                            CategoryId = 3,
                            Name = "Speedloader",
                            Notes = "For loading magazines",
                            Price = 8m,
                            PurchaseDate = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 8,
                            CategoryId = 6,
                            Name = "0.28g BB Bottle",
                            Notes = "Outdoor BBs",
                            Price = 18m,
                            PurchaseDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Airsoft_equipment_tracker.Models.EquipmentItem", b =>
                {
                    b.HasOne("Airsoft_equipment_tracker.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Airsoft_equipment_tracker.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
